services:
  whisper-bazarr-adapter:
    build:
      context: .
      dockerfile: Dockerfile
    image: whisper-bazarr-adapter:local
    container_name: whisper-bazarr-adapter
    ports:
      - "9000:9000"
    environment:
      FWSERVER: "http://faster-whisper:8000"
      FWSERVER_MODEL: ""
      FWSERVER_API_KEY: ""
      FWSERVER_TIMEOUT: "1200"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: whisper
    external: true
